package geicohomepagefooter;

public class GeicoHomePageFooterWebElements {
    public static final String privacyPolicyLocator = "//a[@data-link-name='footer-links-mobile:Privacy']";
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String


    //Test class webelements

    public static final String privacyPageTitle= "//h2[normalize-space()='GEICO RESPECTS YOUR PRIVACY']";
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String
//    public static final String

}
